// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entities.ArchiveOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("活動名稱");

                    b.Property<DateTime>("EventStartTime")
                        .HasColumnType("datetime")
                        .HasComment("活動開始時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記封存");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("活動地址");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("活動地點");

                    b.Property<int>("PurchaseAmount")
                        .HasColumnType("int")
                        .HasComment("購買數量");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("座位號碼ex3排13號");

                    b.Property<string>("StreamingPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("串流平台");

                    b.Property<string>("StreamingUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("串流URL");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("票號");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("money")
                        .HasComment("票價");

                    b.Property<string>("TicketTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("票種名稱");

                    b.HasKey("OrderId");

                    b.ToTable("ArchiveOrders", t =>
                        {
                            t.HasComment("訂單紀錄");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("區域ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("地區名稱");

                    b.HasKey("Id");

                    b.ToTable("Area", null, t =>
                        {
                            t.HasComment("偏好地區列表");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "北北基宜地區"
                        },
                        new
                        {
                            Id = 2,
                            Name = "桃竹苗地區"
                        },
                        new
                        {
                            Id = 3,
                            Name = "雲嘉南地區"
                        },
                        new
                        {
                            Id = 4,
                            Name = "高屏地區"
                        },
                        new
                        {
                            Id = 5,
                            Name = "中彰投地區"
                        },
                        new
                        {
                            Id = 6,
                            Name = "花東地區"
                        },
                        new
                        {
                            Id = 7,
                            Name = "澎金馬地區"
                        },
                        new
                        {
                            Id = 8,
                            Name = "香港"
                        },
                        new
                        {
                            Id = 9,
                            Name = "澳門"
                        },
                        new
                        {
                            Id = 10,
                            Name = "其他地區"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.CategoryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("類別TagID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditeAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記刪除");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("類別Tag名稱");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序預設50");

                    b.HasKey("Id")
                        .HasName("PK_Tags");

                    b.ToTable("CategoryTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7775),
                            EditeAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7776),
                            IsDeleted = false,
                            Name = "音樂",
                            Sort = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7778),
                            EditeAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7778),
                            IsDeleted = false,
                            Name = "戲劇",
                            Sort = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7780),
                            EditeAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7780),
                            IsDeleted = false,
                            Name = "展覽",
                            Sort = 0
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("活動ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasComment("可容納人數");

                    b.Property<string>("CoOrganizer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("協辦單位");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聯絡人欄位JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("活動描述HTML");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasComment("結束時間");

                    b.Property<string>("EventImage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("活動主圖");

                    b.Property<string>("Introduction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("活動簡介");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("資料封存或強制下架");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit")
                        .HasComment("是否免費");

                    b.Property<bool>("IsPrivateEvent")
                        .HasColumnType("bit")
                        .HasComment("是否公開活動");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("緯度");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("活動地址");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("活動地點");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("經度");

                    b.Property<string>("MainOrganizer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("主辦單位");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("活動名稱");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasComment("組織ID");

                    b.Property<string>("ParticipantPeople")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("報名人欄位JSON");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("預設值50");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasComment("開始時間");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("0未發佈1已發佈");

                    b.Property<string>("StreamingPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("串流平台");

                    b.Property<string>("StreamingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("串流網址");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasComment("0線上1實體");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrganizationId" }, "IX_Events_OrganizationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            ContactPerson = "",
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7749),
                            Description = "線上活動描述內容區",
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7750),
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventImage = "https://picsum.photos/1300/600/?random=11",
                            Introduction = "線上活動簡介內容區",
                            IsDeleted = false,
                            IsFree = true,
                            IsPrivateEvent = false,
                            MainOrganizer = "Build School",
                            Name = "【線上直播課】掌握網路三大流量，讓你在同行中脫穎而出",
                            OrganizationId = 1,
                            ParticipantPeople = "[\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=10\",\r\n    \"ParticipantPeopleId\": \"DDDD\"\r\n  },\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=14\",\r\n    \"ParticipantPeopleId\": \"EEEE\"\r\n  },\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=18\",\r\n    \"ParticipantPeopleId\": \"FFFF\"\r\n  }\r\n]\r\n",
                            Sort = 0,
                            StartTime = new DateTime(2024, 4, 5, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7744),
                            Status = (byte)1,
                            StreamingPlatform = "http;",
                            StreamingUrl = "http;",
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1000,
                            ContactPerson = "",
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7758),
                            Description = "實體活動描述內容區",
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7759),
                            EndTime = new DateTime(2024, 4, 5, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7753),
                            EventImage = "https://picsum.photos/1300/600/?random=15",
                            Introduction = "實體活動簡介內容區",
                            IsDeleted = false,
                            IsFree = false,
                            IsPrivateEvent = false,
                            Latitude = "120.33333",
                            LocationAddress = "",
                            LocationName = "大巨蛋",
                            Longitude = "120.33333",
                            MainOrganizer = "卡米地",
                            Name = "【演唱會】五月天",
                            OrganizationId = 2,
                            ParticipantPeople = "[\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=10\",\r\n    \"ParticipantPeopleId\": \"DDDD\"\r\n  },\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=14\",\r\n    \"ParticipantPeopleId\": \"EEEE\"\r\n  },\r\n  {\r\n    \"ParticipantPeopleImage\": \"https://picsum.photos/200/200/?random=18\",\r\n    \"ParticipantPeopleId\": \"FFFF\"\r\n  }\r\n]\r\n",
                            Sort = 0,
                            StartTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7752),
                            Status = (byte)1,
                            Type = (byte)1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.EventAndTagMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("活動與類別對照ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryTagId")
                        .HasColumnType("int")
                        .HasComment("類別TagID");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventID")
                        .HasComment("活動ID");

                    b.HasKey("Id")
                        .HasName("PK_EventAndTagMapping_1");

                    b.HasIndex(new[] { "CategoryTagId" }, "IX_EventAndTagMapping_CategoryTagId");

                    b.HasIndex(new[] { "EventId" }, "IX_EventAndTagMapping_EventID");

                    b.ToTable("EventAndTagMapping", null, t =>
                        {
                            t.HasComment("活動與類別對照");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.HistoryPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<string>("UsedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("使用過的密碼");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryPassword", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.IsPaidRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("付款紀錄ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("訂單ID");

                    b.Property<bool?>("Result")
                        .HasColumnType("bit")
                        .HasComment("付款結果");

                    b.HasKey("Id")
                        .HasName("PK_PaymentDetail");

                    b.ToTable("IsPaidRecords", t =>
                        {
                            t.HasComment("付款紀錄");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.LogInInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("帳號");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("電子郵件");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("密碼");

                    b.HasKey("UserId");

                    b.ToTable("LogInInfo", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("訂單ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聯絡人資料JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記封存");

                    b.Property<bool>("IsDisplayed")
                        .HasColumnType("bit")
                        .HasComment("0不顯示參加活動1顯示");

                    b.Property<string>("ParticipantPeople")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("報名人資料JSON");

                    b.Property<byte>("PaymentType")
                        .HasColumnType("tinyint")
                        .HasComment("0免費1信用卡");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("座位號碼ex3排13號");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("0待付款1成功2付款失敗3取消");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasComment("票券ID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Orders_UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("訂單");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrgFan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("入坑ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FanTime")
                        .HasColumnType("datetime")
                        .HasComment("成為粉絲時間");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasComment("組織ID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrganizationId" }, "IX_OrgFan_OrganizationId");

                    b.HasIndex(new[] { "UserId" }, "IX_OrgFan_UserId");

                    b.ToTable("OrgFan", null, t =>
                        {
                            t.HasComment("組織粉絲");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("組織ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactMobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("聯絡手機");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("聯絡人姓名");

                    b.Property<string>("ContactTelephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("連絡電話");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("組織簡介");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Email");

                    b.Property<string>("Fblink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FBLink")
                        .HasComment("FB連結");

                    b.Property<string>("Igaccount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IGAccount")
                        .HasComment("IG連結");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImgURL")
                        .HasComment("組織形象圖");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記封存");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("組織名稱");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrganizationURL")
                        .HasComment("站內連結");

                    b.Property<string>("OuterUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OuterURL")
                        .HasComment("站外連結");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasComment("擁有者UserId");

                    b.HasKey("Id")
                        .HasName("PK_OrganizationInfo");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Organizations_OwnerId");

                    b.ToTable("Organizations", t =>
                        {
                            t.HasComment("組織");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactMobile = "0123456789",
                            ContactName = "Alice",
                            ContactTelephone = "02-2123-45678",
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7800),
                            Description = "組織簡介內容區",
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7801),
                            IsDeleted = false,
                            Name = "Build School",
                            OrganizationUrl = "HTTP",
                            OwnerId = 0
                        },
                        new
                        {
                            Id = 2,
                            ContactMobile = "0123456789",
                            ContactName = "Bob",
                            ContactTelephone = "02-2123-45678",
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7805),
                            Description = "組織簡介內容區",
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7805),
                            IsDeleted = false,
                            Name = "卡米地",
                            OrganizationUrl = "HTTP",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContactMobile = "0123456789",
                            ContactName = "Charlie",
                            ContactTelephone = "02-2123-45678",
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7808),
                            Description = "組織簡介內容區",
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7808),
                            IsDeleted = false,
                            Name = "海邊的卡夫卡",
                            OrganizationUrl = "HTTP",
                            OwnerId = 3
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrganizationAndUserMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("組織與使用者對照ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasComment("組織ID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id")
                        .HasName("PK_OrganizationUserMapping");

                    b.HasIndex(new[] { "OrganizationId" }, "IX_OrganizationAndUserMapping_OrganizationId");

                    b.HasIndex(new[] { "UserId" }, "IX_OrganizationAndUserMapping_UserId");

                    b.ToTable("OrganizationAndUserMapping", null, t =>
                        {
                            t.HasComment("組織與使用者對照");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.PreFill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("預填資料ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("聯絡地址");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("公司地址");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("公司名稱");

                    b.Property<int?>("CompanyPostalCode")
                        .HasColumnType("int")
                        .HasComment("公司郵遞區號");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("縣市");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("鄉鎮區域");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("手機號碼");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("姓名");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int")
                        .HasComment("郵遞區號");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("職稱");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id")
                        .HasName("PK_Prefill_1");

                    b.HasIndex("UserId");

                    b.ToTable("PreFill", null, t =>
                        {
                            t.HasComment("報名預填資料");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.PreferredActivityArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("偏好區域ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasComment("區域ID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.HasKey("Id")
                        .HasName("PK_PreferredActivityArea_1");

                    b.HasIndex(new[] { "AreaId" }, "IX_PreferredActivityArea_AreaId");

                    b.HasIndex(new[] { "UserId" }, "IX_PreferredActivityArea_UserId");

                    b.ToTable("PreferredActivityArea", null, t =>
                        {
                            t.HasComment("使用者偏好活動區域");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("座位ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記封存");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("座位號碼ex3排13號");

                    b.Property<int>("SeatAreaId")
                        .HasColumnType("int")
                        .HasComment("座位區域ID");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("0可選1已選2不可選");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SeatAreaId" }, "IX_Seats_SeatAreaId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7536),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7537),
                            IsDeleted = false,
                            Number = "1排1號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7540),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7540),
                            IsDeleted = false,
                            Number = "1排2號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7543),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7543),
                            IsDeleted = false,
                            Number = "1排3號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7545),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7546),
                            IsDeleted = false,
                            Number = "1排4號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7547),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7548),
                            IsDeleted = false,
                            Number = "1排5號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7550),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7550),
                            IsDeleted = false,
                            Number = "1排6號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7552),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7553),
                            IsDeleted = false,
                            Number = "1排7號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7555),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7555),
                            IsDeleted = false,
                            Number = "1排8號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7557),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7558),
                            IsDeleted = false,
                            Number = "1排9號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7559),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7560),
                            IsDeleted = false,
                            Number = "1排10號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7562),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7562),
                            IsDeleted = false,
                            Number = "1排11號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7564),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7565),
                            IsDeleted = false,
                            Number = "1排12號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7567),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7567),
                            IsDeleted = false,
                            Number = "1排13號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7569),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7570),
                            IsDeleted = false,
                            Number = "1排14號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7571),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7572),
                            IsDeleted = false,
                            Number = "1排15號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7574),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7574),
                            IsDeleted = false,
                            Number = "1排16號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7576),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7576),
                            IsDeleted = false,
                            Number = "1排17號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7578),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7579),
                            IsDeleted = false,
                            Number = "2排1號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7581),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7581),
                            IsDeleted = false,
                            Number = "2排2號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7583),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7583),
                            IsDeleted = false,
                            Number = "2排3號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7585),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7586),
                            IsDeleted = false,
                            Number = "2排4號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7587),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7588),
                            IsDeleted = false,
                            Number = "2排5號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7590),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7590),
                            IsDeleted = false,
                            Number = "2排6號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7592),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7593),
                            IsDeleted = false,
                            Number = "2排7號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7595),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7595),
                            IsDeleted = false,
                            Number = "2排8號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7597),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7597),
                            IsDeleted = false,
                            Number = "2排9號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7599),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7600),
                            IsDeleted = false,
                            Number = "2排10號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7602),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7602),
                            IsDeleted = false,
                            Number = "2排11號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7604),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7604),
                            IsDeleted = false,
                            Number = "2排12號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7606),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7607),
                            IsDeleted = false,
                            Number = "2排13號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7608),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7609),
                            IsDeleted = false,
                            Number = "2排14號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7611),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7611),
                            IsDeleted = false,
                            Number = "2排15號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7613),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7614),
                            IsDeleted = false,
                            Number = "2排16號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7615),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7616),
                            IsDeleted = false,
                            Number = "2排17號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7618),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7619),
                            IsDeleted = false,
                            Number = "3排1號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7620),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7621),
                            IsDeleted = false,
                            Number = "3排2號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7623),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7623),
                            IsDeleted = false,
                            Number = "3排3號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7625),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7625),
                            IsDeleted = false,
                            Number = "3排4號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7627),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7628),
                            IsDeleted = false,
                            Number = "3排5號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7629),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7630),
                            IsDeleted = false,
                            Number = "3排6號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7632),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7632),
                            IsDeleted = false,
                            Number = "3排7號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7634),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7634),
                            IsDeleted = false,
                            Number = "3排8號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7636),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7637),
                            IsDeleted = false,
                            Number = "3排9號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7638),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7639),
                            IsDeleted = false,
                            Number = "3排10號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7641),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7641),
                            IsDeleted = false,
                            Number = "3排11號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7643),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7643),
                            IsDeleted = false,
                            Number = "3排12號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7645),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7646),
                            IsDeleted = false,
                            Number = "3排13號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7647),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7648),
                            IsDeleted = false,
                            Number = "3排14號",
                            SeatAreaId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7649),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7650),
                            IsDeleted = false,
                            Number = "3排16號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7652),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7652),
                            IsDeleted = false,
                            Number = "3排17號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7654),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7654),
                            IsDeleted = false,
                            Number = "4排1號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7656),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7657),
                            IsDeleted = false,
                            Number = "4排2號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7658),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7659),
                            IsDeleted = false,
                            Number = "4排3號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7660),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7661),
                            IsDeleted = false,
                            Number = "4排4號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7663),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7663),
                            IsDeleted = false,
                            Number = "4排5號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7665),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7665),
                            IsDeleted = false,
                            Number = "4排6號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7667),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7668),
                            IsDeleted = false,
                            Number = "4排7號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7669),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7670),
                            IsDeleted = false,
                            Number = "4排8號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7672),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7673),
                            IsDeleted = false,
                            Number = "4排9號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7674),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7675),
                            IsDeleted = false,
                            Number = "4排10號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7676),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7677),
                            IsDeleted = false,
                            Number = "4排11號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7679),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7679),
                            IsDeleted = false,
                            Number = "4排12號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7681),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7681),
                            IsDeleted = false,
                            Number = "4排13號",
                            SeatAreaId = 1,
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeatArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("座位區域ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("標記封存");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("座位區域名稱");

                    b.HasKey("Id");

                    b.ToTable("SeatAreas");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("票券ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("檢查碼");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("作廢票券");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("票號");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasComment("訂單ID");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int")
                        .HasComment("座位ID");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("0未驗票1驗票成功");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int")
                        .HasComment("票種ID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderId" }, "IX_Tickets_OrderId");

                    b.HasIndex(new[] { "SeatId" }, "IX_Tickets_SeatId");

                    b.HasIndex(new[] { "TicketTypeId" }, "IX_Tickets_TicketTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ApplicationCore.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("票種ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityAmount")
                        .HasColumnType("int")
                        .HasComment("票券數量");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<DateTime>("EndSaleTime")
                        .HasColumnType("datetime")
                        .HasComment("結束販售時間");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasComment("活動ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("強制下架");

                    b.Property<bool>("IsDisplayed")
                        .HasColumnType("bit")
                        .HasComment("是否顯示");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("票種名稱");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasComment("票價");

                    b.Property<byte>("Sort")
                        .HasColumnType("tinyint")
                        .HasComment("預設值50");

                    b.Property<DateTime>("StartSaleTime")
                        .HasColumnType("datetime")
                        .HasComment("開始販售時間");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IX_TicketTypes_EventId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityAmount = 300,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7825),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7826),
                            EndSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7822),
                            EventId = 1,
                            IsDeleted = false,
                            IsDisplayed = false,
                            Name = "Free",
                            Price = 0m,
                            Sort = (byte)0,
                            StartSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7821)
                        },
                        new
                        {
                            Id = 2,
                            CapacityAmount = 50,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7832),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7832),
                            EndSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7829),
                            EventId = 2,
                            IsDeleted = false,
                            IsDisplayed = false,
                            Name = "搖滾票",
                            Price = 6800m,
                            Sort = (byte)0,
                            StartSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7828)
                        },
                        new
                        {
                            Id = 3,
                            CapacityAmount = 200,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7836),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7836),
                            EndSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7835),
                            EventId = 2,
                            IsDeleted = false,
                            IsDisplayed = false,
                            Name = "一般票",
                            Price = 2800m,
                            Sort = (byte)0,
                            StartSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7834)
                        },
                        new
                        {
                            Id = 4,
                            CapacityAmount = 400,
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7840),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7840),
                            EndSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7839),
                            EventId = 2,
                            IsDeleted = false,
                            IsDisplayed = false,
                            Name = "站票",
                            Price = 800m,
                            Sort = (byte)0,
                            StartSaleTime = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7838)
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("使用者ID");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date")
                        .HasComment("生日");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("新增時間");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasComment("修改時間");

                    b.Property<bool>("EdmSubscription")
                        .HasColumnType("bit")
                        .HasComment("訂閱電子報");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasComment("性別");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("帳號照片");

                    b.Property<DateTime?>("LastLogInAt")
                        .HasColumnType("datetime")
                        .HasComment("上次登入時間");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("手機號碼");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("暱稱");

                    b.Property<string>("PersonalProfile")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("個人簡介");

                    b.Property<string>("PersonalUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PersonalURL")
                        .HasComment("個人網址");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("0未驗證EMAIL1已驗證EMAIL");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7472),
                            EditedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7473),
                            EdmSubscription = true,
                            Gender = (byte)1,
                            Image = "https://image.com/alice.jpg",
                            LastLogInAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7458),
                            Mobile = "0912345678",
                            Nickname = "Alice",
                            PersonalProfile = "I'm Alice!",
                            PersonalUrl = "https://alice.com",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1985, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 22, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7478),
                            EdmSubscription = false,
                            Gender = (byte)2,
                            Mobile = "0987654321",
                            Nickname = "Bob",
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1995, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 12, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7517),
                            EditedAt = new DateTime(2024, 3, 20, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7518),
                            EdmSubscription = true,
                            Gender = (byte)2,
                            Image = "https://image.com/charlie.png",
                            LastLogInAt = new DateTime(2024, 3, 17, 17, 27, 31, 686, DateTimeKind.Local).AddTicks(7511),
                            Mobile = "0955555555",
                            Nickname = "Charlie",
                            PersonalProfile = "Hello world!",
                            PersonalUrl = "https://charlie.com",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ArchiveOrder", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithOne("ArchiveOrder")
                        .HasForeignKey("ApplicationCore.Entities.ArchiveOrder", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ArchiveOrders_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Event", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_Organizations");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EventAndTagMapping", b =>
                {
                    b.HasOne("ApplicationCore.Entities.CategoryTag", "CategoryTag")
                        .WithMany("EventAndTagMappings")
                        .HasForeignKey("CategoryTagId")
                        .IsRequired()
                        .HasConstraintName("FK_Event and Tag Mapping_Tags");

                    b.HasOne("ApplicationCore.Entities.Event", "Event")
                        .WithMany("EventAndTagMappings")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_EventAndTagMapping_pEvents");

                    b.Navigation("CategoryTag");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ApplicationCore.Entities.HistoryPassword", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("HistoryPasswords")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HistoryPassword_Users1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LogInInfo", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithOne("LogInInfo")
                        .HasForeignKey("ApplicationCore.Entities.LogInInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrgFan", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Organization", "Organization")
                        .WithMany("OrgFans")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_OrgFan_Organizations");

                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("OrgFans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_OrgFan_Users");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Organization", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "Owner")
                        .WithMany("Organizations")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Organizations_Users");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrganizationAndUserMapping", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Organization", "Organization")
                        .WithMany("OrganizationAndUserMappings")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationAndUserMapping_Organizations");

                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("OrganizationAndUserMappings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationAndUserMapping_Users");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PreFill", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("PreFills")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PreFill_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PreferredActivityArea", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Area", "Area")
                        .WithMany("PreferredActivityAreas")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_PreferredActivityArea_Area");

                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("PreferredActivityAreas")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PreferredActivityArea_Users");

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Seat", b =>
                {
                    b.HasOne("ApplicationCore.Entities.SeatArea", "SeatArea")
                        .WithMany("Seats")
                        .HasForeignKey("SeatAreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Seats_SeatAreas");

                    b.Navigation("SeatArea");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Ticket", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Tickets_Orders");

                    b.HasOne("ApplicationCore.Entities.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .HasConstraintName("FK_Tickets_Seats");

                    b.HasOne("ApplicationCore.Entities.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_TicketTypes");

                    b.Navigation("Order");

                    b.Navigation("Seat");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("ApplicationCore.Entities.TicketType", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_TicketTypes_Events");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Area", b =>
                {
                    b.Navigation("PreferredActivityAreas");
                });

            modelBuilder.Entity("ApplicationCore.Entities.CategoryTag", b =>
                {
                    b.Navigation("EventAndTagMappings");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Event", b =>
                {
                    b.Navigation("EventAndTagMappings");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Navigation("ArchiveOrder");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Organization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("OrgFans");

                    b.Navigation("OrganizationAndUserMappings");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeatArea", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("ApplicationCore.Entities.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Navigation("HistoryPasswords");

                    b.Navigation("LogInInfo");

                    b.Navigation("Orders");

                    b.Navigation("OrgFans");

                    b.Navigation("OrganizationAndUserMappings");

                    b.Navigation("Organizations");

                    b.Navigation("PreFills");

                    b.Navigation("PreferredActivityAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
